project_id = "ffbdcvvxiklzgfwrhbta"

[functions.hubspot-auth]
verify_jwt = false

[functions.hubspot-oauth-exchange]
verify_jwt = false

[functions.sync-hubspot-data]
verify_jwt = false

[functions.api-leaderboard]
verify_jwt = false

[functions.api-me-summary]
verify_jwt = false

[functions.api-session-me]
verify_jwt = false

[functions.api-exchange-session]
verify_jwt = false